@postTest
Feature: Check Skill - POST Request of  LMS API

 	Background:	 Login to LMS Api with valid credential
  	Given Enter with  Login User Name "APIPROCESSING" Passowrd "2xx@Success"
  	When Click Ok button
  	
  Scenario Outline: Create New Skill with unique Skill Id  
  Given LMS API is up and running with Skill Endpoint
    When 	I Hit the POST Request with skill name "<SkillName>"
    Then 	Post Response Success status code is 201
    And 	Displayed Successfuly Created with autogenerated Skill Id
    And 	I Validate the POST response of Skill 
    
  Examples:
  | SkillName  				|
  | Karate            |
	| Katalon           |
  | Cypress           |
  
  Scenario Outline: Create New Skill for Existing Skill name
    Given LMS API is up and running with Skill Endpoint
    When 	I Hit the POST Request with skill name "<SkillName>" 
    Then 	Post Response Failed status code is 400
    And 	Displayed Failed to create Skill
  
  Examples:
  | SkillName   		|
  | dot Net 2       |
  | Karate          |
  | AWS cloud comp  |
  