package LMSApiStepDefinitions;

import static io.restassured.module.jsv.JsonSchemaValidator.matchesJsonSchemaInClasspath;
import static org.hamcrest.Matchers.equalTo;

import com.google.gson.Gson;

import BaseClass.BaseClass;
import LMSApiUtilities.TestContext;
import Models.SkillMapMember;
import io.cucumber.java.After;
import io.cucumber.java.Before;
import io.cucumber.java.Scenario;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;

public class LMSSkillMapPostSteps extends BaseClass{
	RequestSpecification request;
	Response response;
	String jsonBody;
	
	Scenario scn;
	TestContext _textcontext;
	int newskillId;
	String newUserId;
	int newExp;
	
	public LMSSkillMapPostSteps(TestContext testcontext) {
		
		this._textcontext=testcontext;
		
	}
	
	@Before
	public void beforeHook(Scenario s) {
		this.scn=s;
	}
	@After
	public void afterHook(Scenario s) {
		this.scn=s;
		if(_textcontext.get_responseCT()==null) {
			//scn.log("Response : No Rsponse recived");
		}
		else {
			//scn.log("Response: "+response.asString());
		}
			
	}
	@When("I Entered experience {int},skill Id {int},User Id {string} in request body")
	public void i_entered_experience_skill_id_user_id_in_request_body(Integer experience, Integer sId, String uId) {
		SkillMapMember jsonString=new SkillMapMember(experience,sId,uId);
		Gson gson=new Gson();
		jsonBody = gson.toJson(jsonString); 
		newskillId=sId;
		newUserId=uId;
		newExp=experience;
		
	}

	
	@When("I Hit the POST Request of User Skill Map")
	public void i_hit_the_post_request_of_user_skill_map() {
		response = _textcontext.get_requestspecCT()
				.contentType(ContentType.JSON)
				.body(jsonBody).post();
		_textcontext.set_responseCT(response);
	}

	@Then("Displayed Successfuly Created with autogenerated User Skill Id")
	public void displayed_successfuly_created_with_autogenerated_user_skill_id() {
		_textcontext.get_responseCT().then().assertThat().body("skill_id",equalTo(newskillId));
		_textcontext.get_responseCT().then().assertThat().body("skill_id",equalTo(newskillId));
		_textcontext.get_responseCT().then().assertThat().body("months_of_exp",equalTo(newExp));
		scn.log("Respons message of User Skill  : "+_textcontext.get_responseCT().path("message_response").toString());
		scn.log("Newly created User Skill Id   : "+_textcontext.get_responseCT().path("user_skill_id").toString());
	}

	@Then("I Validate the POST response of User Skill")
	public void i_validate_the_post_response_of_user_skill() {
		_textcontext.get_responseCT().then().assertThat().body(matchesJsonSchemaInClasspath("./JsonSchema/SkillMapPostSchema.json"));
		scn.log("User Skill Map - Post request JSON schema validation is Successful");
	}

	@Then("Displayed Failed to create User Skill")
	public void displayed_failed_to_create_user_skill() {
		scn.log("Failed Response Body message is : "+_textcontext.get_responseCT().path("message").toString());
	}


}
